modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "kjscc"
version = "${version}"
displayName = "KubeJS ComputerCraft"
authors = "Prunoideae"
description = '''
Adding support for ComputerCraft from KubeJS.
'''
logoFile = "icon.png"

[[dependencies.kjscc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjscc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjscc]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.68,)"
ordering = "AFTER"
side = "BOTH"